# Generated by Django 4.2 on 2023-08-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('file', models.FileField(upload_to='resource/static/resource')),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField()),
                ('crh', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('course_type', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Elective', 'Elective'), ('Free-Elective', 'Free-Elective')], default='Mandatory', max_length=200)),
                ('resource', models.ManyToManyField(to='resource.resource')),
            ],
        ),
    ]
