# Generated by Django 4.2.5 on 2023-10-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_level_remove_semister_courses_and_more'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='resource',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='semister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.semister'),
        ),
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
