# Generated by Django 4.2 on 2023-10-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_semister_options_and_more'),
        ('resource', '0003_remove_course_rating_remove_resource_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-course_type', 'name']},
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.level'),
        ),
        migrations.AddField(
            model_name='course',
            name='stream',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Engineering', 'Engineering')], default='Applied', max_length=50),
        ),
    ]
