# Generated by Django 4.2 on 2023-10-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_alter_course_options_course_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stream',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Engineering', 'Engineering')], default='Engineering', max_length=50),
        ),
    ]
