# Generated by Django 4.2 on 2023-10-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_department_stream'),
        ('resource', '0005_alter_course_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(to='curriculum.department'),
        ),
    ]
