# Generated by Django 4.2 on 2023-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_remove_course_department_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequest',
            field=models.CharField(default='None', max_length=200, null=True),
        ),
    ]
