# Generated by Django 4.2 on 2023-10-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_remove_course_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='uploadedresource'),
        ),
    ]
