# Generated by Django 4.2.2 on 2023-09-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='profile_pic',
            field=models.ImageField(default='static/images/avatar.png', upload_to='main/static/images/profilepic'),
        ),
    ]
