# Generated by Django 4.2.1 on 2023-09-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_department_school'),
        ('main', '0003_remove_myusers_department_myusers_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='department',
        ),
        migrations.AddField(
            model_name='myusers',
            name='department',
            field=models.ManyToManyField(null=True, to='curriculum.department'),
        ),
    ]
