# Generated by Django 4.2.5 on 2023-09-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_myusers_department_myusers_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='profile_pic',
            field=models.ImageField(default='static/images/avatar.png', upload_to='main/static/profilepic'),
        ),
    ]
