# Generated by Django 4.2.5 on 2023-09-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_myusers_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='profile_pic',
            field=models.ImageField(default='static/images/avatar.png', upload_to='profilepic'),
        ),
    ]
