# Generated by Django 4.2.5 on 2023-10-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_level_remove_semister_courses_and_more'),
        ('main', '0009_alter_myusers_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.level'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='semister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.semister'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.department'),
        ),
    ]
