# Generated by Django 4.2 on 2023-10-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_myusers_level_myusers_semister_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='level',
        ),
    ]
