# Generated by Django 4.2.1 on 2023-09-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semister',
            name='department_name',
        ),
        migrations.AddField(
            model_name='department',
            name='semisters',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.semister'),
        ),
    ]
