# Generated by Django 4.2.1 on 2023-09-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_semister_department_name_department_semisters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='semisters',
        ),
        migrations.AddField(
            model_name='semister',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.department'),
        ),
        migrations.CreateModel(
            name='DepartmentSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department_specific_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.department')),
                ('semester', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.semister')),
            ],
        ),
    ]
