# Generated by Django 4.2.1 on 2023-09-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_remove_department_semisters_semister_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentSemester',
        ),
    ]
