# Generated by Django 4.2.5 on 2023-10-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_department_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('freshman', 'freshman'), ('school', 'school'), ('department', 'department')], default='freshman', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='semister',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='semister',
            name='department',
        ),
    ]
