# Generated by Django 4.2.5 on 2023-09-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0003_message_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atachement',
        ),
    ]
